### ISSUE TITLE
Initial Player

### ISSUE THREAD

**Issue by manglemix** [manglemix/PortalCrawler#1]
**Animations**

- [x] Idle
- [x] 4 Direction Run
- [x] Left Right Attack
- [x] Death

Animations should be in a spritesheet.

**Coding**

- [x] Animation Tree
- [x] Movement Controller
- [x] Attack Damageables
- [x] Create Portals
- [x] Health Component
- [x] Death

**Sounds**

- [x] Swing Sword
- [x] Damaged
- [x] Died

**Comment by TheMasterSlayer** [comment]
![Knight_south_east_idle_sword-Sheet](https://github.com/manglemix/PortalCrawler/assets/160439874/7c262fc7-6c43-49c3-bafe-c5f45e89d812)
![Knight_south_east_swing_sword-Sheet](https://github.com/manglemix/PortalCrawler/assets/160439874/98bdf172-8c8e-45c0-a623-c3fbb9f5ff2e)
![Knight_south_east_walk-Sheet](https://github.com/manglemix/PortalCrawler/assets/160439874/8556db3f-628d-44ba-bf4d-e0ea3e0e530e)
![Knight_south_idle_sword-Sheet](https://github.com/manglemix/PortalCrawler/assets/160439874/067a10cc-41fb-4a52-a122-0474bc0c8fb4)
![Knight_south_swing_sword-Sheet](https://github.com/manglemix/PortalCrawler/assets/160439874/86181bf4-64ef-4123-aa50-3a0cd0b33530)
![Knight_south_walk_sword-Sheet](https://github.com/manglemix/PortalCrawler/assets/160439874/840f328d-804a-4f6e-a46f-65d84f985eb0)
![Knight_west_idle_sword-Sheet](https://github.com/manglemix/PortalCrawler/assets/160439874/5919fa13-8c2b-4e57-8eec-33d4245274ab)
![Knight_west_swing_sword-Sheet](https://github.com/manglemix/PortalCrawler/assets/160439874/16f9283c-6406-45b6-aa83-00fe4965c9d3)
![Knight_west_walk_sword-Sheet](https://github.com/manglemix/PortalCrawler/assets/160439874/eb111c80-fb33-481f-ba39-5202aaa6ebfa)

**Comment by TheMasterSlayer** [comment]
1st row: south-east idle
2nd row: south-east sword swing
3rd row: south-east walk
4th row: south idle
5th row: south sword swing
6th row: south walk
7th row: west idle
8th row: west swing
9th row: west walk

**Comment by TheMasterSlayer** [comment]
![Knight_death-Sheet](https://github.com/manglemix/PortalCrawler/assets/160439874/5f69d01c-fb71-4f0e-8b9b-687a7c9eb927)

**Comment by TheMasterSlayer** [comment]
![Knight_death-Sheet](https://github.com/manglemix/PortalCrawler/assets/160439874/0fd5f718-5008-444c-b45d-2a53fe6dd312)

**Comment by TheMasterSlayer** [comment]
![Knight_death-Sheet](https://github.com/manglemix/PortalCrawler/assets/160439874/8cea20b6-6aa0-44b7-ae80-94e5fea27823)

newest version

**Comment by ATHaz** [comment]
two sound effects for sword attack and laser gun shoot
[sound_effects_player.zip](https://github.com/user-attachments/files/15919857/sound_effects_player.zip)

**Comment by TheMasterSlayer** [comment]
![Knight_sit-Sheet](https://github.com/manglemix/PortalCrawler/assets/160439874/5b51188b-18f8-4a7d-80e8-c85e8f574f16)

**Comment by TheMasterSlayer** [comment]
![Knight_sit-Sheet](https://github.com/manglemix/PortalCrawler/assets/160439874/65f7d7ac-6917-4173-b853-cd21a6064013)
