### ISSUE TITLE
More UI Elements

### ISSUE THREAD

**Issue by manglemix** [manglemix/PortalCrawler#17]
**Art**

- [x] Pause Icon (replace [this one](https://external-content.duckduckgo.com/iu/?u=https%3A%2F%2Fart.pixilart.com%2F72b06a59f06e18f.png&f=1&nofb=1&ipt=eb4038216e23ca5487e450a1c2ecbc6dfe77846bf6a352db32dbf8347a73b3c3&ipo=images))
- [x] Health Bar for bosses (make it a spritesheet from 0 health to 10 health)
- [x] Text box for messages
- [x] Store offering 3 items (price is shown as an icon and a number)

We could also include custom mouse cursors for the following actions:

- [x] Attack
- [x] Deleting a portal
- [x] Regular cursor

**Comment by ATHaz** [comment]
Healthbars all are 100px width and 10px height
![health_bar_default_colorchanging](https://github.com/user-attachments/assets/819d0327-c7c2-44d0-9759-35c23fa91718)
![health_bar_dino](https://github.com/user-attachments/assets/c659f6a6-4dee-4d6d-88b8-f3a06c96135c)
![health_bar_wiz](https://github.com/user-attachments/assets/46e8165c-8de4-4129-9061-5e958f4b06ea)

**Comment by ATHaz** [comment]
pause icon 76
![pause_icon_strip_76frames](https://github.com/user-attachments/assets/3706702a-f687-4912-9814-adc79e1a41a1)
 frames 64px by 64px

**Comment by ATHaz** [comment]
reverse pause icon (to create loop if wanted same settings as above)
![pause_icon_reverse_strip76](https://github.com/user-attachments/assets/6af55b84-4d99-4a6d-a4c9-b3f6caddd3d1)
