### ISSUE TITLE
Initial Portals

### ISSUE THREAD

**Issue by manglemix** [manglemix/PortalCrawler#3]
**Art**

- [x] Idle Portal Animation
- [x] Idle Level Portal Animation

When a portal is created, it instantly opens up. That means there is no animation for it opening up, yet. Animations should be in a spritesheet.

**Coding**

- [x] Portal Creation (max 2)
- [x] Bidirectional teleportation for player
- [x] Bidirectional teleportation for bullets
- [x] Level-to-level Portals (Cancelled)

**Sound**

- [x] Portal Open (plays when the portal opens on a wall, not when a portal is launched from the player)

Incorporating portals into enemy navigation is a non issue for now, but it may involve using NavigationLink. Bidirectional teleportation for the player may naturally work with enemies already as well, but that is not a goal yet.

**Comment by u1404295** [comment]
here are the portals 
[purple + yellow portal.zip](https://github.com/user-attachments/files/15778545/purple.%2B.yellow.portal.zip)
