### ISSUE TITLE
Enemy 0

### ISSUE THREAD

**Issue by manglemix** [manglemix/PortalCrawler#4]
**Art**

- [x] Projectile

**Animations**

- [x] Left Right Run
- [x] Death

There is no real requirement for what the enemy should look like. It just needs to be entry level and fit the theme. Animations should be in a spritesheet.

**Coding**

- [x] Chase the player
- [x] Shoot on line-of-sight, every few seconds
- [x] Health Component
- [x] Death

Ideally the Health Component and Death code is the same as the player.

**Sound**

- [x] Shoot
- [x] Died

**Comment by u1404295** [comment]
Here's the projectile art
[laser projectile zip.zip](https://github.com/user-attachments/files/15754506/laser.projectile.zip.zip)

Note: I have no idea if this is too small or too big

**Comment by ATHaz** [comment]
![branchgrowanimation_tree_enemy_sprite_sheet](https://github.com/manglemix/PortalCrawler/assets/21961871/9789ed11-71c0-4ba4-8cfa-d2bc05afe036)

**Comment by ATHaz** [comment]
idk what we are looking for as an enemy but i made a simple tree sprite that looks pretty bad cuz i couldn't think of anything

**Comment by ATHaz** [comment]
Here is the wizard v1:

**Comment by ATHaz** [comment]
![wizard_enemy](https://github.com/manglemix/PortalCrawler/assets/21961871/5f790220-2faa-4574-a177-7b62f2bf0585)

**Comment by ATHaz** [comment]
![0ddac19f-4638-47e4-84ce-1632f423f8aa](https://github.com/manglemix/PortalCrawler/assets/21961871/deef467e-2dc4-4648-acc9-0d278836f297)
![1a924bf2-65f9-4ed9-8297-46297e8c3e13](https://github.com/manglemix/PortalCrawler/assets/21961871/9a36689a-172a-43d8-a0d7-99763b663bcc)
![1c0aa602-4530-49ae-b2c1-3c2034c2aff5](https://github.com/manglemix/PortalCrawler/assets/21961871/2bafa32d-c7bb-4f18-9fd8-2de2046628b4)
![4dad0abe-f762-455e-8332-f2e53e59d223](https://github.com/manglemix/PortalCrawler/assets/21961871/ab43baf1-5795-476e-aa79-5ffe763cbd75)
![4eb4f5e7-d5e6-4d55-b945-aa24988ed29c](https://github.com/manglemix/PortalCrawler/assets/21961871/bfbbde75-3c75-415d-8338-f96c59e4f649)
![006a3a8d-f697-43db-b1e0-6161dbaba4ab](https://github.com/manglemix/PortalCrawler/assets/21961871/484b1edb-661f-443b-ad42-3f6a45e79614)
![8de8666b-52a4-48ad-9769-9df384a4d29e](https://github.com/manglemix/PortalCrawler/assets/21961871/e7c32ace-c196-4c2e-a6fe-f6ffd8222126)
![8eda5987-57ce-44bc-8dcc-3a4010682c65](https://github.com/manglemix/PortalCrawler/assets/21961871/39561ff2-e829-4ccd-9a67-a09c9fcdd054)
![9df8985f-34f0-470e-a069-31b767ead8a1](https://github.com/manglemix/PortalCrawler/assets/21961871/20b60532-2806-41ad-8c96-de6c31f1811c)
![13cfbb65-e62a-4c77-ab16-bff57c6d6b79](https://github.com/manglemix/PortalCrawler/assets/21961871/75fa1b95-37ad-4479-ad71-0d5347b8a542)
![13e2b5b9-f9e4-4005-b1db-695930ba57b1](https://github.com/manglemix/PortalCrawler/assets/21961871/93da2cca-562c-48fc-8f89-4cfea0968a6e)
![28fcf03f-08db-4921-969c-e8aed572d63d](https://github.com/manglemix/PortalCrawler/assets/21961871/fe6959cf-3bc1-4ece-a394-8cfde271af89)
![33b4cf91-7c70-4c24-a58e-f7992d025277](https://github.com/manglemix/PortalCrawler/assets/21961871/1abf313f-40fa-4c26-99b9-0551a973103e)
![38c2a88c-253a-4021-88cf-370f977df865](https://github.com/manglemix/PortalCrawler/assets/21961871/36049bde-6370-4897-9382-43c35ff11eea)
![39f0d045-42b9-4c89-be49-e91c2f111b58](https://github.com/manglemix/PortalCrawler/assets/21961871/c8a28ab9-c40e-44f0-ab9a-d1ebb5dadb21)
![40b74e23-c135-41d3-a0af-2c3015f0ceb7](https://github.com/manglemix/PortalCrawler/assets/21961871/2bbfc62b-bb2a-4211-8c0c-ce44a37d100a)
![69b27780-393d-4de4-8b2c-12be6643ec29](https://github.com/manglemix/PortalCrawler/assets/21961871/04e548c5-419d-485f-a1f8-60d55b48aabb)
![69f3ed41-b144-4fb4-9310-fa5ca31cd1ad](https://github.com/manglemix/PortalCrawler/assets/21961871/fcde0b38-2e4e-4b37-bc6b-a6c2cc87ff8a)
![129bb625-3fa6-42cb-9b00-c37c1baa0c52](https://github.com/manglemix/PortalCrawler/assets/21961871/b362f487-536e-45b2-87b5-da74a1013ff4)
![353afce2-9157-48c6-8c31-21ad77215252](https://github.com/manglemix/PortalCrawler/assets/21961871/778587a9-c806-4bd5-b331-c3c902ea43d0)
![527d371e-1886-422c-9d3d-654170e19c0c](https://github.com/manglemix/PortalCrawler/assets/21961871/5a47816d-28e8-4e6e-8219-76c81e6d3ef0)
![666d200a-e5bb-4261-bcb1-a0735f37f7e1](https://github.com/manglemix/PortalCrawler/assets/21961871/1c78314e-95ce-4c10-9a66-8a3446e86698)
![8821d435-6955-4226-a009-7aba320acfa5](https://github.com/manglemix/PortalCrawler/assets/21961871/2846a48d-5f02-4fea-9f02-0c2526d3a9fd)
![65578b25-50a6-4894-8f33-7401c8ee42fb](https://github.com/manglemix/PortalCrawler/assets/21961871/66988984-d669-4e16-b803-930f64ca6208)
![626660f7-68eb-458a-888d-0f1022364ad0](https://github.com/manglemix/PortalCrawler/assets/21961871/6c05dc2b-d981-462f-b2e6-62df61b57151)
![781335bc-e38f-4c11-a8c8-36eb10e2a7c5](https://github.com/manglemix/PortalCrawler/assets/21961871/ec11ac6c-daed-47c3-ab56-880eb5233d5e)
![a336c2d2-bb4d-48a9-b446-d3c4a5c07e42](https://github.com/manglemix/PortalCrawler/assets/21961871/bc41983d-8660-456d-b551-254d45c50925)
![b134ab75-a0b2-4776-a0e6-c68b460a3275](https://github.com/manglemix/PortalCrawler/assets/21961871/3506be80-d251-4905-8d1b-16f8c4af0e82)
![b73574fb-e3bf-4acb-9833-344c4141955e](https://github.com/manglemix/PortalCrawler/assets/21961871/fe2dba50-d175-439d-a7af-12944ce8b517)
![bbbeffa5-b1de-4c25-ae7c-0c10dc9821d8](https://github.com/manglemix/PortalCrawler/assets/21961871/c14359bf-6989-4c9b-81a6-d23f43243ccf)
![bd3e880a-b307-403e-8339-54d8bda087f7](https://github.com/manglemix/PortalCrawler/assets/21961871/efc856ac-1be6-4ff6-9c39-b53c0fa7f4cc)
![c67dc1fa-c051-49b8-a94e-f179e32e2b8a](https://github.com/manglemix/PortalCrawler/assets/21961871/43c544cb-c2a7-4d99-8fd6-11f28ae678d9)
![c73f494c-3357-488c-97e0-001c2b457ee7](https://github.com/manglemix/PortalCrawler/assets/21961871/5b410083-8542-43c6-8e8b-1843fbd3ea81)
![c09914fd-e491-4f21-8bed-d434e3ca8a33](https://github.com/manglemix/PortalCrawler/assets/21961871/01bdb14d-c6d1-4005-a1df-8a3d89e3d8ba)
![cf4e9d0f-426c-4d29-9b67-bfcced081202](https://github.com/manglemix/PortalCrawler/assets/21961871/c980e6bf-2ba4-4acf-af39-4feb8fb54e28)
![d0b09110-f3cd-4464-9a93-c85ed9288c59](https://github.com/manglemix/PortalCrawler/assets/21961871/76edf1db-d976-4c94-ba8c-ab51b674d415)
![d329be59-6098-4364-b1bd-059bab5a7268](https://github.com/manglemix/PortalCrawler/assets/21961871/986491fa-6962-4c51-9212-4b209183a033)
![dd851659-d841-484a-9905-b926af9d81a9](https://github.com/manglemix/PortalCrawler/assets/21961871/01b9b8cd-bcd1-49dc-b58b-206b5a8127eb)
![e8525473-ce3f-4de7-9333-124768d248f1](https://github.com/manglemix/PortalCrawler/assets/21961871/8da1fc3c-ce6e-4d11-9168-23553bd7f3e7)
![ef493835-1611-4ae1-b086-98a6c2d4db61](https://github.com/manglemix/PortalCrawler/assets/21961871/7c172ebe-d206-440a-8c81-d2cefee929c4)
![f9f7a0b9-986f-4556-9144-b1dc53a37144](https://github.com/manglemix/PortalCrawler/assets/21961871/333b063c-d851-4e08-a751-0972f156f875)
![f939c72b-dc8a-4166-990c-918058f1f1be](https://github.com/manglemix/PortalCrawler/assets/21961871/a8b3de22-d42b-426c-b57b-9c870b4b088d)
![fc13af30-9bbc-4147-a16f-d76513246e30](https://github.com/manglemix/PortalCrawler/assets/21961871/e26d2412-7679-49c6-864b-4eef36d7e960)

bullet animation for left direction

**Comment by ATHaz** [comment]
![bullet_sheet](https://github.com/manglemix/PortalCrawler/assets/21961871/9bde7171-326d-4137-b1ac-f916e1c298f1)
sprite sheet for bullet

**Comment by ATHaz** [comment]
side version of wizard enemy
![wiz_side](https://github.com/manglemix/PortalCrawler/assets/21961871/48b47e22-bcd5-42df-a2e3-1501e08a47eb)

**Comment by ATHaz** [comment]
dino walk anim (attack animation coming soon)
![dino_enemy_walk_sheet](https://github.com/manglemix/PortalCrawler/assets/21961871/b4683fdd-28c2-4f00-95a6-7fbbe8aff458)

**Comment by ATHaz** [comment]
![enemy_wizard_die_strip](https://github.com/manglemix/PortalCrawler/assets/21961871/cbbaeca5-9e68-4c5e-9fe8-6db7b6462c9d)
46 frames (128px by 128px)
