### ISSUE TITLE
Initial UI

### ISSUE THREAD

**Issue by manglemix** [manglemix/PortalCrawler#5]
**Art**

- [x] Health Indicator
- [ ] Level Counter (unless we decide a text label)

**Coding**

- [x] Responsive Health
- [ ] Responsive Level Counter

**Comment by u1404295** [comment]
here's the health indicator art. when its full and empty. 
[Health indicator (full + empty).zip](https://github.com/user-attachments/files/15755115/Health.indicator.full.%2B.empty.zip)
