### ISSUE TITLE
Player Improvements

### ISSUE THREAD

**Issue by manglemix** [manglemix/PortalCrawler#8]
**Art**

- [x] Corrected Animations
- [x] Portal Projectile

**Coding**

- [x] Fix Portal Glitches
- [x] Create an easy way to pick which portal to replace
- [x] Portal Projectiles
- [x] Fix Player Movement (Walk in one direction and glance off a corner)
- [x] Fix Portal Delay (Levels after the intro add a lot of delay to the portal creation)

**Comment by TheMasterSlayer** [comment]
![death](https://github.com/manglemix/PortalCrawler/assets/160439874/fea10890-a110-40e1-b690-e9c2d2757586)
![idle_down](https://github.com/manglemix/PortalCrawler/assets/160439874/0c99d313-e657-4b30-bc77-01a81bf16444)
![idle_right](https://github.com/manglemix/PortalCrawler/assets/160439874/75408afc-8eb8-4c76-b21a-bdd0506140c1)
![idle_up](https://github.com/manglemix/PortalCrawler/assets/160439874/dbe514fe-da99-4d4d-bae7-a0ff0e05872f)
![swing_down](https://github.com/manglemix/PortalCrawler/assets/160439874/dc48f9f5-1d59-468f-b535-35c04ad93b4f)
![swing_right](https://github.com/manglemix/PortalCrawler/assets/160439874/3ef68696-910b-478b-bd78-ec55f7816756)
![swing_up](https://github.com/manglemix/PortalCrawler/assets/160439874/1a264b8e-5b89-40b1-a45b-994ed6923f2a)
![walk_down](https://github.com/manglemix/PortalCrawler/assets/160439874/61551d52-e96e-4b79-b928-517814c7b828)
![walk_right](https://github.com/manglemix/PortalCrawler/assets/160439874/4d731d3b-2762-4457-a60a-016b49d0e55f)
![walk_up](https://github.com/manglemix/PortalCrawler/assets/160439874/adb3383a-8fca-4dfa-b40b-38a3dad14393)
